trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: GitHub

steps:
- checkout: self
  fetchDepth: 0  # Ensure full repo is fetched

# Set up authentication for Azure DevOps
- script: |
    git config --global user.name "Azure DevOps"
    git config --global user.email "akhalaiashota@outlook.com"
    git config --global credential.helper store
    echo "https://$(System.AccessToken):x-oauth-basic@dev.azure.com" > ~/.git-credentials
    chmod 600 ~/.git-credentials
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Set up Git credentials for Azure DevOps'

# Verify Git Remote
- script: |
    git remote -v
  displayName: 'Verify Git Remote'

# Set up GitHub authentication
- script: |
    git remote add github https://shotalinux:$(GITHUB_PAT)@github.com/$(github_repo).git
  displayName: 'Add GitHub Remote'

# Fetch both main and feature-branch
- script: |
    git fetch github main
    # Check if feature-branch exists locally
    if ! git rev-parse --verify $(branch_name) >/dev/null 2>&1; then
        echo "Feature branch doesn't exist locally, creating it from main..."
        git checkout main
        git pull github main
        git checkout -b $(branch_name)
        git push github $(branch_name)
    else
        echo "Feature branch exists locally, fetching it..."
        git fetch github $(branch_name)
    fi
  displayName: 'Fetch both main and feature-branch'

# Squash the commits of feature-branch into a single commit
- script: |
    git checkout $(branch_name)
    git rebase -i --autosquash github/main
    git push github $(branch_name) --force
  displayName: 'Squash commits from feature-branch'

# Create Pull Request using GitHub API
- script: |
    curl -X POST -H "Authorization: token $(GITHUB_PAT)" \
    -d '{"title": "$(pr_title)", "body": "$(pr_body)", "head": "$(branch_name)", "base": "main"}' \
    https://api.github.com/repos/$(github_repo)/pulls
  displayName: 'Create Pull Request in GitHub'