trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: GitHub

steps:
- checkout: self
  fetchDepth: 0  # Ensure full repo is fetched

# Set up authentication for Azure DevOps
- script: |
    git config --global user.name "Azure DevOps"
    git config --global user.email "akhalaiashota@outlook.com"
    git config --global credential.helper store
    echo "https://$(System.AccessToken):x-oauth-basic@dev.azure.com" > ~/.git-credentials
    chmod 600 ~/.git-credentials
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Set up Git credentials for Azure DevOps'

# Verify Git Remote
- script: |
    git remote -v
  displayName: 'Verify Git Remote'

# Set up GitHub authentication
- script: |
    git remote add github https://shotalinux:$(GITHUB_PAT)@github.com/$(github_repo).git
  displayName: 'Add GitHub Remote'

# Create a new branch and push to GitHub
- script: |
    git checkout -b $(branch_name)
    git push github $(branch_name)
  displayName: 'Create and push branch to GitHub'

# Create Pull Request using GitHub API
- script: |
    curl -X POST -H "Authorization: token $(GITHUB_PAT)" \
    -d '{"title": "$(pr_title)", "body": "$(pr_body)", "head": "$(branch_name)", "base": "main"}' \
    https://api.github.com/repos/$(github_repo)/pulls
  displayName: 'Create Pull Request in GitHub'