trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: GitHub

steps:
- checkout: self
  fetchDepth: 0  # Ensure full repo is fetched

# Set up authentication for Azure DevOps
- script: |
    git config --global user.name "Azure DevOps"
    git config --global user.email "akhalaiashota@outlook.com"
    git config --global credential.helper store
    echo "https://$(System.AccessToken):x-oauth-basic@dev.azure.com" > ~/.git-credentials
    chmod 600 ~/.git-credentials
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  displayName: 'Set up Git credentials for Azure DevOps'

# Verify Git Remote
- script: |
    git remote -v
  displayName: 'Verify Git Remote'

# Set up GitHub authentication
- script: |
    git remote add github https://shotalinux:$(GITHUB_PAT)@github.com/$(github_repo).git
  displayName: 'Add GitHub Remote'

# Fetch master from Azure DevOps and feature branch from GitHub
- script: |
    # Fetch master branch from Azure DevOps (default)
    git fetch origin master
    # Check if feature-branch exists on GitHub
    if git ls-remote --exit-code github refs/heads/$(branch_name); then
        echo "Feature branch exists on GitHub, overwriting it with Azure DevOps master..."
        git checkout master
        git pull origin master  # Ensure we have the latest master from Azure DevOps
        git push github master:$(branch_name) --force  # Force push to overwrite feature-branch on GitHub
    else
        echo "Feature branch doesn't exist on GitHub, creating it from Azure DevOps master..."
        git checkout master
        git pull origin master  # Ensure we have the latest master from Azure DevOps
        git checkout -b $(branch_name)
        git push github $(branch_name)
    fi
  displayName: 'Fetch master from Azure DevOps and feature-branch from GitHub'

# Squash the commits of feature-branch into a single commit
- script: |
    git checkout $(branch_name)
    git rebase --autosquash github/main
    git push github $(branch_name) --force
  displayName: 'Squash commits from feature-branch'

# Create Pull Request using GitHub API
- script: |
    curl -X POST -H "Authorization: token $(GITHUB_PAT)" \
    -d '{"title": "$(pr_title)", "body": "$(pr_body)", "head": "$(branch_name)", "base": "main"}' \
    https://api.github.com/repos/$(github_repo)/pulls
  displayName: 'Create Pull Request in GitHub'