name: Linode instance Tests

on:
  workflow_dispatch:

jobs:
  test-module:
    uses: ./.github/workflows/common-terragrunt.yml
    with:
      tf_version: 'latest'
      tg_version: '0.68.5'
      tg_dir: 'TgLab/environments/linode/instanceV2'
    secrets: inherit
