name: SonarCloud Scan
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main  # Trigger on pushes to the main branch
  # pull_request:
  #   types: [opened, synchronize]  # Trigger on PRs

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud to analyze the full history

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
