name: AZ vnet unit tests

on:
  workflow_dispatch:

jobs:
  test-module:
    uses: ./.github/workflows/common-terragrunt-unit.yml
    with:
      tf_version: 'latest'
      tg_version: '0.72.4'
      tg_dir: 'TgLab/environments/azure/vnet-unit'
    secrets: inherit # Pass all secrets from the parent workflow
